spring:
  application:
    name:
      spring-redis-demo
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-wait: 1000ms
          max-idle: 8
          min-idle: 0
